#!/usr/bin/env python3
"""Generate Prometheus recording rules and Grafana alert rules from alerts_config.json.

Writes three files, all of which are overwritten wholesale and must not be hand-edited:
  config/recording_rules.yml       Prometheus recording rules (physical-drive set, growth, projection)
  config/alert_rules.yml           Grafana unified alerting rules
  config/notification_policies.yml Grafana notification routing

Run from anywhere; paths resolve relative to this file.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent
CONFIG_DIR = REPO_ROOT / "config"
CONFIG_PATH = CONFIG_DIR / "alerts_config.json"
RECORDING_RULES_PATH = CONFIG_DIR / "recording_rules.yml"
ALERT_RULES_PATH = CONFIG_DIR / "alert_rules.yml"
NOTIFICATION_POLICIES_PATH = CONFIG_DIR / "notification_policies.yml"

GENERATED_HEADER = (
    "# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY\n"
    "# This file is generated by generate_alerts.py\n"
    "# To make changes, edit config/alerts_config.json and run: python3 generate_alerts.py\n\n"
)

# Grafana templating expanded at notification time. Kept as plain strings so the
# surrounding f-strings do not need doubled braces.
LBL_MOUNTPOINT = "{{ $labels.mountpoint }}"
LBL_HOSTNAME = "{{ $labels.hostname }}"
LBL_INSTANCE = "{{ $labels.instance }}"
LBL_JOB = "{{ $labels.job }}"
LBL_GPU = "{{ $labels.gpu }}"
VALUE = "{{ $value }}"

# Lookback for the scrape watchdog. Must stay below watchdog_alerts.sustained_duration
# so that stale series from a renamed target age out before the `for` elapses; validated
# in validate().
WATCHDOG_QUERY_RANGE_SECONDS = 120

# Labels that identify one filesystem on one host. Every projection rule joins on
# exactly this set, so they must all be produced by the same `by` clause.
FS_LABELS = "hostname, instance, device, mountpoint"

DURATION_PATTERN = re.compile(r"^(\d+)([smhd])$")
DURATION_MULTIPLIERS = {"s": 1, "m": 60, "h": 3600, "d": 86400}


def _represent_str(dumper: yaml.Dumper, data: str) -> yaml.ScalarNode:
    """Emit multi-line strings as literal blocks so generated PromQL stays readable."""
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


yaml.add_representer(str, _represent_str)


def parse_duration_to_seconds(duration: str) -> int:
    """Convert a Prometheus-style duration ('10s', '5m', '1h', '7d') to seconds."""
    match = DURATION_PATTERN.match(duration)
    if not match:
        raise ValueError(f"Invalid duration format: {duration!r} (expected e.g. '30s', '15m', '6h', '7d')")

    value, unit = int(match.group(1)), match.group(2)
    return value * DURATION_MULTIPLIERS[unit]


def seconds_to_duration(seconds: int) -> str:
    """Render seconds as the largest whole Prometheus duration unit that fits exactly."""
    for unit, multiplier in (("d", 86400), ("h", 3600), ("m", 60)):
        if seconds >= multiplier and seconds % multiplier == 0:
            return f"{seconds // multiplier}{unit}"
    return f"{seconds}s"


def duration_to_days(duration: str) -> int:
    """Convert a whole-day duration such as '28d' to an integer day count."""
    seconds = parse_duration_to_seconds(duration)
    if seconds % 86400 != 0:
        raise ValueError(f"Expected a whole number of days, got {duration!r}")
    return seconds // 86400


def physical_drive_selector(drives_cfg: dict) -> str:
    """Build the PromQL label selector that defines a monitored physical drive.

    An allowlist of local block-backed filesystem types, not a denylist: a disk is
    ext4/xfs on the host that owns it and nfs4/cifs everywhere it is mounted
    remotely, so this counts each drive exactly once across all hosts with no
    per-host mountpoint lists. A future sshfs/s3fs mount would slip through a
    denylist; here the unknown is excluded by default.
    """
    fstypes = "|".join(drives_cfg["fstypes"])
    return f'fstype=~"{fstypes}",mountpoint!~"{drives_cfg["mountpoint_exclude_regex"]}"'


def build_recording_rules(config: dict) -> dict:
    """Build the Prometheus recording rule groups."""
    selector = physical_drive_selector(config["physical_drives"])
    projection_cfg = config["storage_projection_alerts"]
    intervals = config["recording_rule_intervals"]

    growth_window = projection_cfg["growth_window"]
    confirm_window = projection_cfg["confirm_window"]
    growth_days = duration_to_days(growth_window)
    confirm_days = duration_to_days(confirm_window)

    growth_metric = f"fs:physical:growth_bytes_per_day_{growth_window}"
    confirm_metric = f"fs:physical:growth_bytes_per_day_{confirm_window}"

    def growth_expr(window: str, days: int) -> str:
        # Difference of two 1-day averages `window` apart, rather than a least-squares
        # fit over one window. predict_linear weights a single bulk copy or delete as
        # heavily as steady growth, so one 6 TB delete flipped /home to "emptying" and
        # one bulk ingest made /mnt/data2 look like it would die in 14 days. Averaging
        # each endpoint over a day means a burst can move at most one endpoint.
        return (
            f"(\n    avg_over_time(fs:physical:used_bytes[1d])\n"
            f"    - avg_over_time(fs:physical:used_bytes[1d] offset {window})\n"
            f"  ) / {days}"
        )

    # Every rule in this group reads the RAW node_filesystem metrics, never another
    # recorded series. Recording rules do not emit staleness markers, so a rule that
    # instant-selects a recorded series keeps finding the previous sample inside the
    # 5-minute lookback window and writes a fresh one from it, forever. Chaining
    # `fs:physical:used_bytes` off `fs:physical:size_bytes` made unmounted drives and
    # renamed mountpoints report indefinitely and alert on drives that no longer
    # exist. Deriving from raw metrics lets staleness propagate, so a drive that stops
    # being scraped disappears within one lookback window.
    #
    # The range-based rules in the projection group below MAY read these recorded
    # series: a range selector returns only real samples, so it cannot self-perpetuate.
    size = f"max by ({FS_LABELS}) (node_filesystem_size_bytes{{{selector}}})"
    avail = f"max by ({FS_LABELS}) (node_filesystem_avail_bytes{{{selector}}})"

    return {
        "groups": [
            {
                "name": "physical_drives",
                "interval": intervals["physical_drives"],
                "rules": [
                    {"record": "fs:physical:size_bytes", "expr": size},
                    {"record": "fs:physical:avail_bytes", "expr": avail},
                    {"record": "fs:physical:used_bytes", "expr": f"{size}\n  - {avail}"},
                    {"record": "fs:physical:used_percent", "expr": f"100 * (\n    1 - {avail}\n    / {size}\n  )"},
                ],
            },
            {
                "name": "storage_projection",
                "interval": intervals["storage_projection"],
                "rules": [
                    {"record": growth_metric, "expr": growth_expr(growth_window, growth_days)},
                    {"record": confirm_metric, "expr": growth_expr(confirm_window, confirm_days)},
                    {
                        # Absent when a drive is not filling, which is why the alert that
                        # consumes it sets noDataState: OK. Clamped so an almost-flat
                        # drive reports a bounded horizon instead of millions of days.
                        "record": "fs:physical:days_until_full",
                        "expr": (
                            f"clamp_max(\n"
                            f"    avg_over_time(fs:physical:avail_bytes[1d]) / ({growth_metric} > 0),\n"
                            f"    730\n"
                            f"  )"
                        ),
                    },
                ],
            },
        ]
    }


def build_alert(
    uid: str,
    title: str,
    expr: str,
    summary: str,
    description: str,
    threshold: float,
    alert_type: str,
    cfg: dict,
    evaluator_type: str = "gt",
    no_data_state: str = "OK",
    query_range_seconds: int = 600,
) -> dict:
    """Create a Grafana unified alert rule: query A, reduce to B, threshold to C.

    query_range_seconds is the lookback Grafana reduces over. It matters more than it
    looks: a series that stops being produced (a renamed target, a relabeled
    mountpoint) stays in the range result for this long, and `last` then reduces it to
    its final value. If that value breaches the threshold and the window outlives the
    rule's `for`, the rule fires on a series that no longer exists. Keep the window
    shorter than sustained_duration for any rule whose absent state is a breach.
    """
    return {
        "uid": uid,
        "title": title,
        "condition": "C",
        "data": [
            {
                "refId": "A",
                "relativeTimeRange": {"from": query_range_seconds, "to": 0},
                "datasourceUid": "prometheus",
                "model": {
                    "expr": expr,
                    "interval": "",
                    "refId": "A",
                    "datasource": {"type": "prometheus", "uid": "prometheus"},
                },
            },
            {
                "refId": "B",
                "relativeTimeRange": {"from": 0, "to": 0},
                "datasourceUid": "-100",
                "model": {
                    "datasource": {"type": "__expr__", "uid": "-100"},
                    "expression": "A",
                    "reducer": "last",
                    "refId": "B",
                    "type": "reduce",
                },
            },
            {
                "refId": "C",
                "relativeTimeRange": {"from": 0, "to": 0},
                "datasourceUid": "-100",
                "model": {
                    "datasource": {"type": "__expr__", "uid": "-100"},
                    "conditions": [
                        {
                            "evaluator": {"params": [threshold], "type": evaluator_type},
                            "operator": {"type": "and"},
                            "query": {"params": ["B"]},
                            "type": "query",
                        }
                    ],
                    "expression": "B",
                    "refId": "C",
                    "type": "threshold",
                },
            },
        ],
        # Per-rule rather than hardcoded: a presence-based alert whose metric is
        # absent while healthy must treat missing data as OK, while the watchdog
        # must treat missing data as a problem.
        "noDataState": no_data_state,
        "execErrState": "Alerting",
        "for": cfg["sustained_duration"],
        "annotations": {"summary": summary, "description": description},
        "labels": {"alert_type": alert_type},
        "isPaused": False,
    }


def build_alert_groups(config: dict) -> list[dict]:
    """Build Grafana alert rule groups, one group per alert type so each gets its own interval."""
    intervals = config["rule_group_intervals"]
    rules_by_type: dict[str, list[dict]] = {alert_type: [] for alert_type in intervals}

    if config["watchdog_alerts"]["enabled"]:
        cfg = config["watchdog_alerts"]

        # Two distinct failures, deliberately two rules.
        #
        # 1. A configured target that cannot be scraped -> up == 0.
        # 2. A whole job that has disappeared from the config -> absent(up{job=...}).
        #
        # It is tempting to fold the second into the first with noDataState: Alerting,
        # but that latches PERMANENTLY. Grafana never resolves an alert instance whose
        # series has vanished when noDataState is Alerting, so every target that is ever
        # renamed or removed leaves a false "down" alert firing forever. Verified on
        # Grafana 12.3: three renamed targets stayed Alerting indefinitely.
        rules_by_type["watchdog"].append(
            build_alert(
                uid="scrape-target-down-alert",
                title="Scrape Target Down",
                # Covers every configured target, so a new host is watched the moment
                # it is added. This is the gap that let DCGM sit dead for 7 weeks.
                expr="up",
                summary=f"Monitoring target {LBL_JOB} at {LBL_INSTANCE} is down",
                description=(
                    f"Prometheus cannot scrape {LBL_JOB} at {LBL_INSTANCE}. "
                    "Metrics and every alert derived from them are stale for that target."
                ),
                threshold=1,
                alert_type="watchdog",
                cfg=cfg,
                evaluator_type="lt",
                no_data_state="OK",
                # Deliberately shorter than sustained_duration. A removed or renamed
                # target leaves up=0 samples behind, and with the default 600s window
                # those outlive a 5m `for` and page for a target that was merely
                # renamed. A short window lets them age out first, while a target that
                # is really down keeps producing up=0 and still fires.
                query_range_seconds=WATCHDOG_QUERY_RANGE_SECONDS,
            )
        )

        # absent() yields a series carrying the job label when nothing matches, and
        # nothing at all when the job is present, so this is presence-based and cannot
        # latch on a per-instance series.
        required_jobs = cfg["required_jobs"]
        absent_expr = "\n  or ".join(f'absent(up{{job="{job}"}})' for job in required_jobs)

        rules_by_type["watchdog"].append(
            build_alert(
                uid="monitoring-job-missing-alert",
                title="Monitoring Job Missing",
                expr=absent_expr,
                summary=f"No targets at all are configured for job {LBL_JOB}",
                description=(
                    f"Prometheus has no targets for the required job {LBL_JOB}. Either the scrape config "
                    "lost them or Prometheus failed to load it, and nothing is being collected."
                ),
                threshold=0,
                alert_type="watchdog",
                cfg=cfg,
                no_data_state="OK",
                query_range_seconds=WATCHDOG_QUERY_RANGE_SECONDS,
            )
        )

    if config["memory_alerts"]["enabled"]:
        cfg = config["memory_alerts"]
        threshold = cfg["threshold_percent"]
        rules_by_type["system"].append(
            build_alert(
                uid="memory-usage-alert",
                title="Memory Usage Alert",
                expr="100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
                summary=f"Memory usage on {LBL_HOSTNAME} has been above {threshold}% for {cfg['sustained_duration']}",
                description=f"Memory usage on {LBL_HOSTNAME} is {VALUE}%, above the {threshold}% threshold",
                threshold=threshold,
                alert_type="system",
                cfg=cfg,
            )
        )

    if config["storage_alerts"]["enabled"]:
        cfg = config["storage_alerts"]
        threshold = cfg["threshold_percent"]
        rules_by_type["storage"].append(
            build_alert(
                uid="storage-alert-physical-drives",
                title="Storage Alert",
                expr="fs:physical:used_percent",
                summary=f"{LBL_MOUNTPOINT} on {LBL_HOSTNAME} is more than {threshold}% full",
                description=f"{LBL_MOUNTPOINT} on {LBL_HOSTNAME} is {VALUE}% full",
                threshold=threshold,
                alert_type="storage",
                cfg=cfg,
            )
        )

    if config["storage_projection_alerts"]["enabled"]:
        cfg = config["storage_projection_alerts"]
        days = cfg["days_until_full_threshold"]
        confirm_metric = f"fs:physical:growth_bytes_per_day_{cfg['confirm_window']}"
        min_used = cfg["min_used_percent"]

        # Three conditions must hold together. The short-window horizon alone is what
        # made the old alert fire after a bulk ingest and keep firing after a cleanup.
        projection_expr = (
            f"fs:physical:days_until_full\n"
            f"  and on({FS_LABELS}) ({confirm_metric} > 0)\n"
            f"  and on({FS_LABELS}) (fs:physical:used_percent > {min_used})"
        )

        rules_by_type["storage_projection"].append(
            build_alert(
                uid="storage-projection-alert",
                title="Storage Projection Alert",
                expr=projection_expr,
                summary=f"{LBL_MOUNTPOINT} on {LBL_HOSTNAME} is projected to fill within {days} days",
                description=(
                    f"{LBL_MOUNTPOINT} on {LBL_HOSTNAME} has {VALUE} days of headroom left. "
                    f"Its {cfg['growth_window']} and {cfg['confirm_window']} growth trends both point up "
                    f"and it is more than {min_used}% full."
                ),
                threshold=days,
                alert_type="storage_projection",
                cfg=cfg,
                evaluator_type="lt",
            )
        )

    if config["gpu_temperature_alerts"]["enabled"]:
        cfg = config["gpu_temperature_alerts"]
        threshold = cfg["threshold_celsius"]
        rules_by_type["gpu"].append(
            build_alert(
                uid="gpu-temperature-alert",
                title="GPU Temperature Alert",
                expr="DCGM_FI_DEV_GPU_TEMP",
                summary=f"GPU {LBL_GPU} on {LBL_HOSTNAME} has been above {threshold}C for {cfg['sustained_duration']}",
                description=f"GPU {LBL_GPU} temperature is {VALUE}C, above the {threshold}C threshold",
                threshold=threshold,
                alert_type="gpu",
                cfg=cfg,
            )
        )

    if config["gpu_memory_alerts"]["enabled"]:
        cfg = config["gpu_memory_alerts"]
        threshold = cfg["threshold_percent"]
        rules_by_type["gpu"].append(
            build_alert(
                uid="gpu-memory-alert",
                title="GPU Memory Alert",
                expr="DCGM_FI_DEV_FB_USED / (DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE) * 100",
                summary=(
                    f"GPU {LBL_GPU} memory on {LBL_HOSTNAME} has been above {threshold}% "
                    f"for {cfg['sustained_duration']}"
                ),
                description=f"GPU {LBL_GPU} memory usage is {VALUE}%, above the {threshold}% threshold",
                threshold=threshold,
                alert_type="gpu",
                cfg=cfg,
            )
        )

    if config["gpu_xid_alerts"]["enabled"]:
        cfg = config["gpu_xid_alerts"]
        rules_by_type["gpu"].append(
            build_alert(
                uid="gpu-xid-error-alert",
                title="GPU XID Error Alert",
                expr="DCGM_FI_DEV_XID_ERRORS",
                summary=f"GPU {LBL_GPU} on {LBL_HOSTNAME} reported an XID error",
                description=f"GPU {LBL_GPU} reported XID error code {VALUE}, indicating a hardware or driver fault",
                threshold=0,
                alert_type="gpu",
                cfg=cfg,
            )
        )

    return [
        {
            "orgId": 1,
            "name": f"{alert_type}_alerts",
            "folder": "Server Monitoring",
            "interval": intervals[alert_type],
            "rules": rules,
        }
        for alert_type, rules in rules_by_type.items()
        if rules
    ]


def build_notification_policies(config: dict) -> dict:
    """Route each alert type to its own Slack contact point with its own repeat interval."""
    intervals = config["rule_group_intervals"]

    def repeat_interval_for(alert_type: str, alert_cfg: dict) -> str:
        # Grafana waits repeat_interval AFTER the evaluation that (re)sends, so the
        # observed gap between Slack messages is repeat_interval + one group interval.
        # Subtract the group interval so the configured value is what users actually see.
        group_seconds = parse_duration_to_seconds(intervals[alert_type])
        notify_seconds = parse_duration_to_seconds(alert_cfg["notification_interval"])
        return seconds_to_duration(max(notify_seconds - group_seconds, group_seconds))

    def route(alert_type: str, receiver: str, alert_cfg: dict) -> dict:
        return {
            "receiver": receiver,
            "matchers": [f"alert_type={alert_type}"],
            "group_by": ["alertname", "hostname", "mountpoint"],
            "group_wait": "0s",
            "group_interval": intervals[alert_type],
            "repeat_interval": repeat_interval_for(alert_type, alert_cfg),
        }

    return {
        "apiVersion": 1,
        "policies": [
            {
                # Default route. alert_type=system lands here; every other type is
                # matched by a more specific route below.
                "receiver": "slack-alerts-system",
                "group_by": ["alertname", "hostname"],
                "group_wait": "0s",
                "group_interval": intervals["system"],
                "repeat_interval": repeat_interval_for("system", config["memory_alerts"]),
                "routes": [
                    route("watchdog", "slack-alerts-system", config["watchdog_alerts"]),
                    route("storage", "slack-alerts-storage", config["storage_alerts"]),
                    route(
                        "storage_projection",
                        "slack-alerts-storage-projection",
                        config["storage_projection_alerts"],
                    ),
                    route("gpu", "slack-alerts-gpu", config["gpu_temperature_alerts"]),
                ],
            }
        ],
    }


def validate(config: dict) -> None:
    """Fail before writing anything if the config is internally inconsistent."""
    intervals = config["rule_group_intervals"]

    alert_types = {
        "watchdog_alerts": "watchdog",
        "memory_alerts": "system",
        "storage_alerts": "storage",
        "storage_projection_alerts": "storage_projection",
        "gpu_temperature_alerts": "gpu",
        "gpu_memory_alerts": "gpu",
        "gpu_xid_alerts": "gpu",
    }

    for key, alert_type in alert_types.items():
        cfg = config[key]
        if not cfg["enabled"]:
            continue

        sustained = parse_duration_to_seconds(cfg["sustained_duration"])
        group = parse_duration_to_seconds(intervals[alert_type])
        if sustained != 0 and sustained < group:
            raise ValueError(
                f"{key}: sustained_duration ({cfg['sustained_duration']}) is shorter than the "
                f"{alert_type} rule group interval ({intervals[alert_type]}), so it cannot be evaluated"
            )

        notify = parse_duration_to_seconds(cfg["notification_interval"])
        if notify < group:
            raise ValueError(
                f"{key}: notification_interval ({cfg['notification_interval']}) is shorter than the "
                f"{alert_type} rule group interval ({intervals[alert_type]})"
            )

        for percent_key in ("threshold_percent", "min_used_percent"):
            if percent_key in cfg and not 0 <= cfg[percent_key] <= 100:
                raise ValueError(f"{key}: {percent_key} must be between 0 and 100, got {cfg[percent_key]}")

    watchdog = config["watchdog_alerts"]
    if watchdog["enabled"]:
        sustained = parse_duration_to_seconds(watchdog["sustained_duration"])
        if sustained <= WATCHDOG_QUERY_RANGE_SECONDS:
            raise ValueError(
                f"watchdog_alerts: sustained_duration ({watchdog['sustained_duration']}) must exceed the "
                f"{WATCHDOG_QUERY_RANGE_SECONDS}s query window, or a renamed target's leftover up=0 "
                "samples will fire the watchdog before they age out"
            )

    projection = config["storage_projection_alerts"]
    if projection["enabled"]:
        growth = parse_duration_to_seconds(projection["growth_window"])
        confirm = parse_duration_to_seconds(projection["confirm_window"])
        if confirm <= growth:
            raise ValueError(
                f"storage_projection_alerts: confirm_window ({projection['confirm_window']}) must be longer "
                f"than growth_window ({projection['growth_window']}) for it to act as confirmation"
            )


def write_yaml(path: Path, document: dict) -> None:
    with path.open("w") as handle:
        handle.write(GENERATED_HEADER)
        yaml.dump(document, handle, default_flow_style=False, sort_keys=False, width=1000)


def main() -> None:
    with CONFIG_PATH.open() as handle:
        config = json.load(handle)

    validate(config)

    write_yaml(RECORDING_RULES_PATH, build_recording_rules(config))

    alert_groups = build_alert_groups(config)
    write_yaml(ALERT_RULES_PATH, {"apiVersion": 1, "groups": alert_groups})

    write_yaml(NOTIFICATION_POLICIES_PATH, build_notification_policies(config))

    rule_count = sum(len(group["rules"]) for group in alert_groups)
    print(f"Generated {rule_count} alert rules in {len(alert_groups)} groups, plus recording rules.")


if __name__ == "__main__":
    main()
